title: K. S. Shin
description: Tomorrow will be better than today.
github_url: https://github.com/KS-Sh1n
twitter_url: https://twitter.com/korean_bluefrog
linkedin_url: https://t.ly/920P
facebook_url: ""
instagram_url: ""
permalink: /:categories/:title/
google_analytics: ""
remote_theme: pages-themes/cayman@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one 