title: K. S. Shin
description: Tomorrow will be better than today.
github_url: https://t.ly/ymel
twitter_url: https://t.ly/AypN
linkedin_url: https://t.ly/920P
facebook_url: ""
instagram_url: ""
permalink: /:categories/:title/
google_analytics: ""
remote_theme: pages-themes/cayman@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one 