# Change 'comments' to true for Disqus comments
disqus:
  comments: true
  disqus_shortname: 'millennial-3'

# If you are not using Google Analytics, please change 'google-ID' to an empty string
google-ID: 'G-P95LLKJLSB'

menu:
- {name: 'About',       url: 'about'}
- {name: 'Development', url: 'dev'}
- {name: 'NFT',         url: 'nft'}
- {name: 'DeFi',        url: 'defi'}
- {name: 'Thoughts',    url: 'thoughts'}
- {name: 'Readings',    url: 'readings'}

# Available social icons are powered by Font Awesome, so you can use any icon that they offer
social:
- {icon: 'twitter', link:    'https://twitter.com/korean_bluefrog'}
# - {icon: 'facebook', link:   'https://www.facebook.com/paululele'}
# - {icon: 'instagram', link:  'https://instagram.com/paululele'}
- {icon: 'envelope', link:   'sksoup3819@gmail.com'}
# - {icon: 'rss-square', link: 'feed.xml'}
# - {icon: 'rss-square', link: 'rss-feed.xml'}

# Customize site text
pagination:
  next_page: 'Next'
  previous_page: 'Previous'

sharing_button_prompt: 'Spread this feed!'
related_posts: 'Another articles...'
post_date_prefix: 'Written on: '