# Change 'comments' to true for Disqus comments
disqus:
  comments: true
  disqus_shortname: 'millennial-3'

# If you are not using Google Analytics, please change 'google-ID' to an empty string
google-ID: 'G-P95LLKJLSB'

menu:
- {name: 'About',       url: 'about'}
- {name: 'Development', url: 'dev'}
- {name: 'Games',         url: 'games'}
- {name: 'DeFi',        url: 'defi'}
- {name: 'Thoughts',    url: 'thoughts'}
- {name: 'Threads',    url: 'threads'}

# Available social icons are powered by Font Awesome, so you can use any icon that they offer
social:
- {icon: 'twitter', link:    'https://twitter.com/bemodestdoteth'}
- {icon: 'instagram', link:  'https://www.instagram.com/bemosest.eth/'}
- {icon: 'envelope', link:   'sksoup3819@gmail.com'}
# - {icon: 'facebook', link:   'https://www.facebook.com/paululele'}
# - {icon: 'rss-square', link: 'feed.xml'}
# - {icon: 'rss-square', link: 'rss-feed.xml'}

# Customize site text
pagination:
  next_page: 'Next'
  previous_page: 'Previous'

sharing_button_prompt: 'Spread this feed!'
related_posts: 'Another articles...'
post_date_prefix: 'Written on: '

cover:  "about.png"